server:
  port: 8888


#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG


spring:
  datasource:
    password: 'ooffyy663399'
    url: jdbc:mysql://ofy-mysql-1:3306/ofy
    username: ofy

#spring:
#  datasource:
#    password: ''
#    url: jdbc:mysql://localhost:3306/ofy
#    username: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  resources:
    static-locations: classpath:/static/
  servlet:
    multipart:
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true


amazonProperties:
  endpointUrl: https://s3.us-east-1.amazonaws.com
  accessKey: AKIAZROWR4YJZHW3PWXI
  secretKey: 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
  bucketName: ofy-images

application:
  s3-endpoint: https://ofy-images:s3.ap-south-1.amazonaws.com
