#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG


spring:
  datasource:
    password: aaryan
    url: jdbc:mysql://localhost:3306/ofy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: aaryan

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  resources:
    static-locations: classpath:/static/
  servlet:
    multipart:
      file-size-threshold: 300KB
      max-file-size: 300KB
      max-request-size: 1MB
      enabled: true

amazonProperties:
  endpointUrl: https://s3.us-east-1.amazonaws.com
  accessKey:  AKIAX4SXYJ4HBB37PN6S
  secretKey: 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
  bucketName: ofy-images

application:
  s3-endpoint: https://${S3_BUCKET_NAME}:s3.ap-south-1.amazonaws.com #Decouple Zone

server:
  port: 8888


