#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG



spring:
  datasource:
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USER_NAME}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  resources:
    static-locations: classpath:/static/
  servlet:
    multipart:
      file-size-threshold: 300KB
      max-file-size: 300KB
      max-request-size: 1MB
      enabled: true

amazonProperties:
  endpointUrl: https://s3.us-east-1.amazonaws.com
  accessKey:  ${S3_ACCESS_KEY}
  secretKey: ${S3_SECRET_KEY}
  bucketName: ${S3_BUCKET_NAME}

application:
  s3-endpoint: https://${S3_BUCKET_NAME}:s3.ap-south-1.amazonaws.com #Decouple Zone

server:
  port: 8888
